#!/usr/bin/python
# -*- coding: utf-8 -*-

import requests
import re
import csv
import time

def get_PTC(url):
	r = requests.get(url, timeout=30)
	r.raise_for_status
	r.encoding = r.apparent_encoding
	html = r.text
	urls = []
	result = re.findall(r'<dd><a href="/(.*?)">', html, re.S)
	for i in result:
		urls.append('https://www.southampton.ac.uk' + '/' + i)
	return urls

def getData(url):
	info = []
	r = requests.get(url, timeout=30)
	r.raise_for_status
	r.encoding = r.apparent_encoding
	html = r.text
	try:
		data1 = re.search(r'<em class="hyphen"> </em>(.*?)</h1>',html, re.S)
		tle = data1.group(1)
	except:
		tle = '100'

	try:
		data2 = re.search(r'Typical entry requirements</h4>(.*?)</p>',html, re.S)
		entry = data2.group(1)
	except:
		entry = '200'

	try:
		data3 = re.search(r'>International.*?</td><td>(.*?)</td><td>(.*?)</td><td>(.*?)</td><td>(.*?)</td><td>(.*?)</td></tr><tr><td>',html, re.S)
		year = data3.group(2)
		mode = data3.group(3)
		fees = data3.group(5)
	except:
		year = '300'
		mode = '400'
		fees = '500'

	try:
		data4 = re.search(r'<h3>International applicants</h3>.*?<li>(.*?)</li>',html, re.S)
		lan = data4.group(1)
	except AttributeError as e:
		try:
			data4 = re.search(r'IELTS(.*?)</p>', html, re.S)
			lan = data4.group(1)
		except AttributeError as e:
			try:
				data4 = re.search(r'<h4>English Language Requirement</h4><p>(.*?)</p>', html, re.S)
				lan = data4.group(1)
			except AttributeError as e:
				try:
					data4 = re.search(r'English Language Proficiency</strong></p>(.*?)</p><p>', html, re.S)
					lan = data4.group(1)
				except:
					lan = '600'

	try:
		data5 = re.search(r'<title>(.*?)</title>', html, re.S)
		acd = data5.group(1)
	except:
		acd = '700'

	info.append(tle)
	info.append(acd)
	info.append(year)
	info.append(entry)
	info.append(lan)
	info.append(mode)
	info.append(fees)
	info.append(url)
	return info

def write_to_csv(data):
    out = open('SouthAmpton.csv', 'a', newline='',encoding='utf-8')#csv文件写入链接时需要指定编码格式为utf-8
    csv_write = csv.writer(out, dialect='excel')
    csv_write.writerow(data)


if __name__ == '__main__':
	url = 'https://www.southampton.ac.uk/courses/taught-postgraduate.page'
	urls = get_PTC(url)
	count = 1
	for i in urls[250:]:
		print("正在获取第{n}个页面数据".format(n=count))
		gift = getData(i)
		print("正在写入第{n}个页面数据".format(n=count))
		write_to_csv(gift)
		count = count + 1
		time.sleep(1.5)
